package LANraragi::Plugin::Metadata::HitomiDownloader;

use strict;
use warnings;

use LANraragi::Model::Plugins;
use LANraragi::Utils::Archive qw(is_file_in_archive extract_file_from_archive);
use LANraragi::Utils::Logging qw(get_plugin_logger);
use LANraragi::Utils::String  qw(trim);

my $metadata_file = "info.txt";

# Korean field name mappings
my %FIELD_MAP = (
    "\x{AC24}\x{B7EC}\x{B9AC} \x{B118}\x{BC84}" => 'gallery_number',    # 갤러리 넘버
    "\x{C81C}\x{BAA9}"                             => 'title',            # 제목
    "\x{C791}\x{AC00}"                             => 'artist',           # 작가
    "\x{ADF8}\x{B8F9}"                             => 'group',            # 그룹
    "\x{D0C0}\x{C785}"                             => 'type',             # 타입
    "\x{C2DC}\x{B9AC}\x{C988}"                     => 'series',           # 시리즈
    "\x{CE90}\x{B9AD}\x{D130}"                     => 'character',        # 캐릭터
    "\x{D0DC}\x{ADF8}"                             => 'tags',             # 태그
    "\x{C5B8}\x{C5B4}"                             => 'language',         # 언어
);

sub plugin_info {
    return (
        name        => "hitomi_downloader info.txt",
        type        => "metadata",
        namespace   => "hitomi-dl-info",
        author      => "LANraragi",
        version     => "1.0",
        description => "Parses info.txt files generated by hitomi_downloader (Korean format)",
        parameters  => {
            'replace_title' => { type => "bool", desc => "Replace the title with the one in the metadata file" },
        },
    );
}

sub get_tags {
    my ( undef, $lrr_info, $params ) = @_;
    my $logger = get_plugin_logger();

    my $archive = $lrr_info->{file_path};
    my %hashdata;

    # Auto-Plugin runs across the whole library; most archives won't carry a
    # hitomi_downloader info.txt. Treating "file not in archive" as an error
    # floods the log with failures on every non-hitomi archive. Downgrade to
    # a silent skip here — a libarchive read failure (distinct from simply
    # not-present) still raises so real corruption isn't hidden.
    my $path_in_archive;
    eval { $path_in_archive = is_file_in_archive( $archive, $metadata_file ); };
    if ( my $err = $@ ) {
        chomp $err;
        die "Could not read archive '$archive': $err\n";
    }
    unless ($path_in_archive) {
        $logger->info("No hitomi_downloader info.txt in archive; skipping.");
        return ();
    }

    %hashdata = read_file( extract_file_from_archive( $archive, $path_in_archive ) );

    if ( !$params->{'replace_title'} ) { delete $hashdata{'title'} }

    $logger->info( "Sending the following tags to LRR: " . ( $hashdata{tags} // '' ) );

    return %hashdata;
}

sub read_file {
    my ($metafile) = @_;

    open( my $fh, '<:encoding(UTF-8)', $metafile )
      or die "Could not open $metafile!\n";

    my %fields;
    while ( my $line = <$fh> ) {
        $line = trim($line);
        next if !$line;

        if ( $line =~ /^(.+?):\s*(.*)$/ ) {
            my $key   = trim($1);
            my $value = trim($2);

            # Skip blank and placeholder values once, here, instead of per-field below.
            next if $value eq '' || $value eq 'N/A';

            if ( exists $FIELD_MAP{$key} ) {
                $fields{ $FIELD_MAP{$key} } = $value;
            }
        }
    }
    close($fh);
    unlink($metafile);

    my %hashdata;
    my @tags;

    # Title
    if ( defined $fields{title} ) {
        $hashdata{title} = $fields{title};
    }

    # Source
    if ( defined $fields{gallery_number} ) {
        push @tags, "source:hitomi.la/galleries/$fields{gallery_number}.html";
    }

    # Artist
    if ( defined $fields{artist} ) {
        push @tags, "artist:$fields{artist}";
    }

    # Group
    if ( defined $fields{group} ) {
        push @tags, "group:$fields{group}";
    }

    # Type (category)
    if ( defined $fields{type} ) {
        push @tags, "category:$fields{type}";
    }

    # Series (parody) — "original" means no parody, skip it.
    if ( defined $fields{series} && $fields{series} ne 'original' ) {
        push @tags, "parody:$fields{series}";
    }

    # Character
    if ( defined $fields{character} ) {
        push @tags, "character:$fields{character}";
    }

    # Tags (preserve explicit namespaces; normalize bare values)
    if ( defined $fields{tags} ) {
        for my $tag ( split( /,\s*/, $fields{tags} ) ) {
            $tag = trim($tag);
            next unless length $tag;
            next if $tag =~ /:\s*$/;
            push @tags, $tag =~ /^[^:]+:.+$/ ? $tag : "tag:$tag";
        }
    }

    # Language
    if ( defined $fields{language} ) {
        push @tags, "language:$fields{language}";
    }

    $hashdata{tags} = join( ', ', sort @tags );

    return %hashdata;
}

1;
